# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fdb50180e8208aee0a04e9326dbf6418"
name = "qr-code-app"
handle = "qr-code-app-321"
application_url = "https://leave-integral-geek-thumb.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://leave-integral-geek-thumb.trycloudflare.com/auth/callback",
  "https://leave-integral-geek-thumb.trycloudflare.com/auth/shopify/callback",
  "https://leave-integral-geek-thumb.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
